---
# This template will be my main one. It will be use for all my testing template. 
AWSTemplateFormatVersion: '2010-09-09'
Description: |-
  Create EC2 instance resource
  Create Security Group resource [open port 80 to the internet
  lock down port 22 to your personal IP address]
  Create an Elastic IP resource
  Attach your Security Group and Elastic IP resource to your EC2 instance
  Attach SG and EIP to EC2 instance
  Create Mappings for ImageId to dynamically map the imageid w/ the region
  Create a Parameter for the following EC2 properties [Imageid,Keyname,subnetid,SececurityGroupIds].
  Create an Outputs section in your tempalte to display the Security Group Name or ID,
  EC2 instance of your resource
Metadata:
  Authors:
    Description: Joseph Mbatchou 
Parameters:
  MyVPC:
    Description: VPC to operate in the region 
    Type: AWS::EC2::VPC::Id  #this identifier will list all VPCs
  MySubnetID:
    Description: Subnet IDs
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: 'AWS::SSM::Parameter::Value<String>' # Parameter store 
    Default: Dev-EC2-InstanceType
    
  KeyName:
    Description: Name of existing EC2 KeyPair to enable SSH access to new instances
    Type: AWS::EC2::KeyPair::KeyName #pulls all keys u have in Region/identifier
    ConstraintDescription: must be the name of an existing EC2 keypair
  SecurityGroupIds:
    Description: All security group in my Region
    Type:  "List<AWS::EC2::SecurityGroup::Id>"
  
Mappings:
  RegionMap:
    us-west-1:
      "HVM64": "ami-0f5e8a042c8bfcd5e"
    us-west-2:
      "HVM64":  "ami-094125af156557ca2" 
    us-east-2:
      "HVM64": "ami-0beaa649c482330f7" 
    eu-west-1:
      "HVM64": "ami-01cae1550c0adea9c"
    ap-southeast-1:
      "HVM64": "ami-0af2f764c580cc1f9"
    ap-northeast-1:
      "HVM64": "ami-08a8688fb7eacb171"
    us-east-1:
      "HVM64": "ami-0b0dcb5067f052a63" 
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref AWS::Region, HVM64]
      InstanceType: !Ref InstanceType
      SubnetId: !Ref MySubnetID
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroupIds
      Tags:
        - Key: Name
          Value: WebServer
        - Key: Name
          Value: WebServerTest
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl start httpd
          systemctl enable httpd
          echo " <html> <head>
             <h2 style="font-size: 5rem; color:red">JOE BAHO CLOUD</h2>
             </head>
               <body>
               <h1 style="font-size: 2rem; color: black"> You successfully access Joseph Mbatchou web page.
                 </h1>
                 <h1 style="font-size: 1.5rem; color: blue"> Welcome here and we hope you will enjoy!.
                   </h1> </body>
                    </html> " > /var/www/html/index.html

       